// Generated by Selenium IDE

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class BuscarpageTest {
    private static WebDriver driver;

    static String baseURL;

    @BeforeClass
    public static void setUp() {
        System.setProperty("webdriver.google.driver", "C:\\Avenga\\Automation\\chromedriver.exe");
        driver = new ChromeDriver();
        baseURL = "https://google.com.ar";

    }

    @AfterClass
    public static void tearDown() {
        driver.quit();
    }

    @Test
    public void buscarpage() {
        driver.get(baseURL);
        driver.manage().window().maximize();
        driver.findElement(By.name("q")).sendKeys("avenga");
        driver.findElement(By.name("q")).click();
        driver.close();
    }
}
